echoserver:
  name: echoserver
  image: ealen/echo-server:latest
  replicas: 1
  containerPort: 80
  serviceType: ClusterIP
  servicePort: 80
  path: /echo
  pathType: Exact
helloworld:
  name: helloworld
  image: tutum/hello-world:latest
  replicas: 1
  containerPort: 80
  serviceType: ClusterIP
  servicePort: 80
  path: /hello
  pathType: Exact
pgadmin:
  name: pgadmin
  image: dpage/pgadmin4
  replicas: 1
  containerPort: 80
  serviceType: ClusterIP
  servicePort: 80
  path: /pgadmin
  pathType: Prefix
  email: patiphan.t@appman.co.th
  password: admin
  scriptname: /pgadmin
ingress:
  name: ingress-ctl
  host: newnlb-539ca90222a3f06f.elb.ap-southeast-1.amazonaws.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/rewrites: "serviceName=pgadmin-svc rewrite=/pgadmin"